# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v2
    - name: Print environment variables
      run: |
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
        echo "MYSQL_DATABASE=$MYSQL_DATABASE"
        echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
